---
language: python
python: "2.7"

sudo: required

env:
  - PHP_VERSION=5.5
  - PHP_VERSION=5.6
  - PHP_VERSION=7.0
  - PHP_VERSION=hhvm

install:
  - pip install ansible
  - cd tests/
  - echo -e "[defaults]\nroles_path = ../../\nhostfile = inventory" > ansible.cfg
  - echo "localhost" > inventory

script:
  - tests/test.sh
