---
- name: ensure composer package is installed
  package:
    name: "{{ php_package_composer }}"
  when: php_package_composer is defined

- name: ensure composer installer is downloaded
  get_url:
    url: https://getcomposer.org/installer
    dest: /usr/local/bin/install-composer
    mode: 0755
  when: php_package_composer is not defined

- name: ensure composer is installed
  command: php /usr/local/bin/install-composer --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer
  when: php_package_composer is not defined
