---
- name: "ensure yum/dnf repository is installed"
  package:
    name: "{{ php_repository }}"
  when: php_repository is defined

- name: "ensure yum/dnf repositories are enabled"
  lineinfile:
    dest: "/etc/yum.repos.d/{{ item }}.repo"
    regexp: "^enabled="
    line: "enabled=1"
  with_items: "{{ php_repositories | default([]) }}"
