---
- name: "ensure php cli is configured"
  template:
    src: php.ini.j2
    dest: "{{ php_config_dir }}/cli/conf.d/90-custom.ini"
  sudo: yes

- name: "ensure php-fpm is configured"
  template:
    src: php.ini.j2
    dest: "{{ php_config_dir }}/fpm/conf.d/90-custom.ini"
  sudo: yes
  when: php_fpm == true
  notify: "restart php-fpm"

- name: "ensure php for apache is configured"
  template:
    src: php.ini.j2
    dest: "{{ php_config_dir }}/apache/conf.d/90-custom.ini"
  sudo: yes
  when: php_web_server == "apache"
  notify: "restart web server"
