---
- include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}/{{ php_version }}.yml"
    - "{{ ansible_distribution|lower }}/dist.yml"

- include: install/repository_apt.yml
  when: ansible_pkg_mgr == 'apt' and php_version

- include: install/repository_yum.yml
  when: "ansible_pkg_mgr in ['yum', 'dnf'] and php_version"

- include: install/packages.yml

- include: fpm.yml
  when: php_fpm

- include: config.yml

- include: webserver/nginx.yml
  when: php_fpm
