---
- name: "ensure hhvm runs as configured user"
  lineinfile:
    dest: "{{ php_hhvm_service_config_file }}"
    regexp: "^#?RUN_AS_USER="
    line: "RUN_AS_USER=\"{{ php_fpm_user }}\""
  when: php_fpm_user is not none
  notify: "restart hhvm"

- name: "ensure hhvm runs as configured group"
  lineinfile:
    dest: "{{ php_hhvm_service_config_file }}"
    regexp: "^#?RUN_AS_GROUP="
    line: "RUN_AS_GROUP=\"{{ php_fpm_group }}\""
  when: php_fpm_group is not none
  notify: "restart hhvm"

- name: "ensure hhvm listens on configured port"
  lineinfile:
    dest: "{{ php_hhvm_server_config_file }}"
    regexp: "^;?hhvm.server.port ="
    line: "hhvm.server.port = {{ php_hhvm_port }}"
  notify: "restart hhvm"

- name: "ensure timezone for hhvm is configured"
  lineinfile:
    dest: "{{ php_hhvm_config_file }}"
    line: "date.timezone = {{ php_timezone }}"

- name: "ensure hhvm service is enabled and running"
  service:
    name: hhvm
    state: started
    enabled: yes
